[project]
name = "asynccachedview"
version = "0.0.1"
authors = [
  { name="Alexander Sosedkin", email="monk@unboiled.info" },
]
description = "Make asynchronous requests, online and offline"
urls.homepage = "https://github.com/t184256/asynccachedview"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]
requires-python = ">=3.11"
dependencies = [
    "aiosqlite",
    "aiohttp",
    "aiosqlitemydataclass@git+https://github.com/t184256/aiosqlitemydataclass#egg=8788f856e84e8b4b25d5c16230a09829ee397a0b",
] # TODO: list python dependencies
optional-dependencies.test = [
    "pytest",
    "coverage", "pytest-cov",
    "mypy", "pytest-mypy",
    "ruff",
    "pytest-asyncio",
    "aioresponses",
]

[tool.pytest.ini_options]
# TODO: reenable mypy
addopts = "--cov --cov-report term-missing --doctest-modules"

[tool.coverage]
run.source = [ "asynccachedview" ]
run.branch = true
report.exclude_lines = [
  "# pragma: no cover",
  "if __name__ == .__main__.:",
  "if typing.TYPE_CHECKING:",
]
report.fail_under = 100

[tool.mypy]
strict = true

[tool.ruff]
line-length = 79
select = [ "ALL" ]
ignore = [
  "D105",  # undocumented-magic-method
  "D203",  # one-blank-line-before-class
  "D213",  # multi-line-summary-second-line
  "S101",  # assert
  "FIX002",  # line-contains-todo
  "FIX004",  # line-contains-hack
  "TD002",  # missing-todo-author
  "TD003",  # missing-todo-link
  # TODO: reenable mypy
  "ANN",  # type checking
]
per-file-ignores."tests/**" = [
  "INP001",  # implicit-namespace-package
  "S101",  # assert
  "SLF001",  # private-member-access
]
flake8-quotes.inline-quotes = "single"
flake8-quotes.multiline-quotes = "single"
flake8-copyright.notice-rgx = '# SPDX-FileCopyrightText: 2023 Alexander Sosedkin <monk@unboiled.info>\n# SPDX-License-Identifier: GPL-3.0\n'
preview = true

[tool.ruff.format]
quote-style = "single"
preview = true
